[[redirects]]
  from = "/leads/leverandor"
  to = "/leads/leverandor.html"
  status = 200
  force = true

[[headers]]
  for = "/leads/leverandor.html"
  [headers.values]
    Basic-Auth = "leverandor:superhemmeligtkodeord"
